### ISSUE TITLE
h5 file not found (perhaps not annotated) when trying to train in Google Colab

### ISSUE THREAD

**Issue by lnbeloate** [AlexEMG/DeepLabCut-Workshop-Materials#10]
I used DLC-CPU GUI to open and label frames then uploaded folder to Google Drive, then used Google Colab to train the network ('Colab_TrainNetwork_VideoAnalysis').

These are my 'labeled-data' files:
![image](https://user-images.githubusercontent.com/56928455/84940956-3ea0b280-b0a6-11ea-96e5-f2c3761b473f.png)

I edited the project_path and video_sets in the config file:
![image](https://user-images.githubusercontent.com/56928455/84941103-7a3b7c80-b0a6-11ea-9b79-f08cf17facd7.png)

When I run the 'train network' section, I get this error (TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"; h5 file not found):
![image](https://user-images.githubusercontent.com/56928455/84941191-a0611c80-b0a6-11ea-891e-f10a6a955347.png)

I've tried different iterations, tried suggestions I've found from other users, and even tried starting over from scratch but I'm still getting the same error.

**Comment by MMathisLab** [comment]
two things: (1) the labeled folder is just for you to visually inspect, not needed. only the original file and the CollectedData_yourname.h5 is need;

(2) don't change the path from the original video path name, ONLY the project path. And, you have / and. \ which will not work ;)

**Comment by MMathisLab** [comment]
check out this video; https://www.youtube.com/watch?v=DRT-Cq2vdWs

**Comment by lnbeloate** [comment]
It's now working.. thank you!
