### ISSUE TITLE
pdf files are not available.

### ISSUE THREAD

**Issue by EstherXSD** [AlexEMG/DeepLabCut-Workshop-Materials#12]
Hi I found that pdf files in the DeepLabCut-Workshop-Materials are not available.
Specifically, part1-labeling.pdf part2-network.pdf and part3-analysis.pdf. 
Is it possible to renew these files for us?
Thanks a lot!

**Comment by MMathisLab** [comment]
Hi! For me they are there! If you click on the file you can click download, or download the whole repo.

**Comment by EstherXSD** [comment]
Thanks! This time I can open them and download the files!
