### ISSUE TITLE
DataJoint/DLC integration?

### ISSUE THREAD

**Issue by CBroz1** [AlexEMG/DeepLabCut-Workshop-Materials#13]
DISCUSSION QUESTION:

- What is your question?

The `DLCcourse.md` file has a link on [Line 116](https://github.com/DeepLabCut/DeepLabCut-Workshop-Materials/edit/master/DLCcourse.md#L116) to a [page that 404s](https://github.com/DeepLabCut/DeepLabCut-Workshop-Materials/blob/master/datajoint.io). Was there previously more documentation on DLC/DataJoint integration? Should this instead point to the [DataJoint Tutorial](https://tutorials.datajoint.io/)?

- What resources have you considered? (list papers, videos, blog searches, etc).

Searched across other DLC repos for references to DataJoint

**Comment by AlexEMG** [comment]
Thanks for pointing that out -- it was just a link to DataJoint, and I fixed it.

Regarding DLC/DataJoint integration, @MMathisLab has shared a scheme: https://github.com/MMathisLab/dj-mathis-sharing

**Comment by CBroz1** [comment]
Thanks!

**Comment by CBroz1** [comment]
As a follow-up: DataJoint now offers direct support for managing DLC workflows  via [Element DeepLabCut](https://github.com/datajoint/element-deeplabcut). Many thanks to the Mathis team for sharing the repo mentioned above
