### ISSUE TITLE
Broken Colab Notebook links

### ISSUE THREAD

**Issue by auesro** [AlexEMG/DeepLabCut-Workshop-Materials#14]
DISCUSSION QUESTION:

- What is your question?

Links to Colab Notebooks https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb and https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb lead to `Error 404 This is not the web page you are looking for`.

**Comment by AlexEMG** [comment]
Thanks! I fixed one link in the Readme, where are the other broken ones?

**Comment by auesro** [comment]
Oh sorry! Gave you the links but not their location, my bad!
They are in the [DLCcourse.md](https://github.com/DeepLabCut/DeepLabCut-Workshop-Materials/blob/master/DLCcourse.md). In the section: `June 5th RECAP: AFTER LABELING (ACTION/WATCH)`
