### ISSUE TITLE
inappropriate file name prevent clonnning on Windows

### ISSUE THREAD

**Issue by DenisPolygalov** [AlexEMG/DeepLabCut-Workshop-Materials#2]
This file: https://github.com/AlexEMG/DeepLabCut-Workshop-Materials/blob/master/DeepLabCut-WhatNext%3F.pdf 
contain "?" character in it's name.
This is not allowd on Windows and therefore 'git clone' command will fail 
for this repository when executed on Windows host.

**Comment by AlexEMG** [comment]
Thanks for pointing that out, changed the name.
