### ISSUE TITLE
Error in creating new project

### ISSUE THREAD

**Issue by catalbergaria** [AlexEMG/DeepLabCut-Workshop-Materials#6]
Hi, in the Manage Project tab of the DLC GUI, trying to create a new project, after naming the project, experimenter and choosing a couple of videos, I get this error in the terminal: 

![Capture](https://user-images.githubusercontent.com/66469414/83864216-5712e380-a71c-11ea-9fa0-042b3e6df77b.PNG)

**Comment by eoverton** [comment]
Are you running a command prompt on Windows? I've had the same problem, but after I ran command prompt as an administrator, this error disappeared.

**Comment by MMathisLab** [comment]
> OSError: symbolic link privilege not held. This error is specific to the users of Windows operating system. Open command prompt with administrative rights. Use `Run as administrator' while opening the command prompt.

https://github.com/DeepLabCut/DeepLabCut/wiki/Troubleshooting-Tips

**Comment by catalbergaria** [comment]
Thanks, that worked :)
