### ISSUE TITLE
web GUI 'ERR_CONNECTION_REFUSED'

### ISSUE THREAD

**Issue by lnbeloate** [AlexEMG/DeepLabCut-Workshop-Materials#7]
When trying to open new web GUI, I am receiving the following error: ERR_CONNECTION_REFUSED. I've tried turning off firewall, changing Chrome settings, no proxy network. I also didn't have this issue with the first iteration of the web GUI that was sent during the workshop. Is there something I'm missing?

![DLC error](https://user-images.githubusercontent.com/56928455/84178777-9b6af000-aa4a-11ea-8bf2-d752f97bbff5.jpg)

**Comment by AlexEMG** [comment]
Thanks for raising this issue, we are reworking the GUI and it will be up soon! Stay tuned.

**Comment by AlexEMG** [comment]
Check this updated GUI out: http://contrib.deeplabcut.org/
