### ISSUE TITLE
Config file not found error in terminal

### ISSUE THREAD

**Issue by aloksneurobot1** [AlexEMG/DeepLabCut-Workshop-Materials#9]
hi i feel this to be very basic but, unfortunately i still have this error

windows 10 , anaconda terminal, using gui of maDLC  to create new project
I could create new project , but when i tried to click on to edit config file i had the following error. 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\anaconda3\lib\site-packages\deeplabcut\gui\create_new_project.py in edit_config(self, event)
    290                 pass
    291             else:
--> 292                 raise FileNotFoundError("File not found!")
    293
    294     def select_videos(self, event):

FileNotFoundError: File not found!

after seeing this error i did check the subfolders created by DLC and i could see the config file which i could open in google chrome but not edit it.
is there any other way to edit config file except for gui option ?

**Comment by MMathisLab** [comment]
Hi @aloksneurobot1 you can edit the file in any text editor, but it should be totally work in the GUI  as long as the file is there; do you see the file in the project folder you created?

**Comment by aloksneurobot1** [comment]
Yes I do see the file in the project folder. I will try to edit it notepad to add the bodyparts list as u had suggested in workshop module 1. 
Thank you !!

**Comment by MMathisLab** [comment]
No problem, let me know if that issue continues though; it might be you have no default software to open "yaml" files! If you want a cool free one: check out "Atom" https://atom.io/ this is what I use :)
